// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editorActions': string;
  'editorContainer': string;
  'editorText': string;
  'icon': string;
}
export const cssExports: CssExports;
export default cssExports;
