// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cols': string;
  'rows': string;
}
export const cssExports: CssExports;
export default cssExports;
