// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createPollContainer': string;
  'options': string;
  'optionsContainer': string;
  'pollContainer': string;
  'renderOption': string;
  'renderOptions': string;
  'renderPollContainer': string;
  'renderQuestion': string;
}
export const cssExports: CssExports;
export default cssExports;
