// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'createPollContainer': string;
  'inputElement': string;
  'label': string;
  'options': string;
  'optionsContainer': string;
  'pollContainer': string;
  'previewContainer': string;
  'previewOption': string;
  'previewOptions': string;
  'previewQuestion': string;
  'resultContainer': string;
  'resultOption': string;
  'resultOptionTitle': string;
  'resultOptionVotes': string;
  'resultOptionsContainer': string;
  'resultParticipants': string;
  'resultQuestions': string;
  'showHidePreview': string;
  'titleText': string;
  'titleTextContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
