// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordianContainer': string;
  'accordianHeader': string;
  'accordianHeaderTitle': string;
  'displayPanel': string;
  'hidePanel': string;
}
export const cssExports: CssExports;
export default cssExports;
