// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeTab': string;
  'deactiveTab': string;
  'tabContainer': string;
  'tabContent': string;
  'tabContentContainer': string;
  'tabListContainer': string;
  'tabsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
