// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hourHand': string;
  'minuteHand': string;
  'secondHand': string;
  'watchCenter': string;
  'watchContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
