// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activePlayer': string;
  'activePlayerName': string;
  'instructions': string;
  'playerScores': string;
  'snakeLadderGameContainer': string;
  'snakeLadderGameControls': string;
  'snakeLadderGameStage': string;
}
export const cssExports: CssExports;
export default cssExports;
