// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'choice': string;
  'choiceContainer': string;
  'gameContianer': string;
  'girdRow': string;
  'gridContainer': string;
  'gridSections': string;
  'showWinText': string;
}
export const cssExports: CssExports;
export default cssExports;
