import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import ToolTipRenderComponent from "../components/Tooltip";

import Sidebar from "../components/Sidebar";

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar />
      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
