// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'carouselContainer': string;
  'carouselControls': string;
  'carouselControlsLeft': string;
  'carouselControlsRight': string;
  'carouselDotControlItem': string;
  'carouselDotControls': string;
  'carouselMediaSection': string;
  'carouselSlide': string;
  'carouselTextSection': string;
  'mediaControls': string;
}
export const cssExports: CssExports;
export default cssExports;
