// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkBoxContainer': string;
  'checkBoxIcon': string;
  'checkBoxInput': string;
  'checkedIcon': string;
  'disabledCheckBox': string;
  'labelContainer': string;
  'mixedIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
