import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';

function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div>About Page</div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default About
