// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  columnActive: string;
  columnContainer: string;
  columnDisabled: string;
  gridContainer: string;
  gridRowContainer: string;
}

export const cssExports: CssExports;
export default cssExports;
