// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'left': string;
  'right': string;
  'toolTipText': string;
  'tooltipContainer': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
