// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'progressBar': string;
  'progressBarBar': string;
  'progressBarContainer': string;
  'progressBarLabel': string;
  'round': string;
  'square': string;
}
export const cssExports: CssExports;
export default cssExports;
