// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  gridCol: string;
  gridRow: string;
}

export const cssExports: CssExports;
export default cssExports;
