// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deactive': string;
  'dragBorder': string;
  'pagination': string;
  'paginationContainer': string;
  'rowStyle': string;
  'searchContainer': string;
  'searchInput': string;
  'settingsActions': string;
  'settingsContainer': string;
  'settingsRow': string;
  'settingsTitle': string;
  'showSettings': string;
  'sortableIconActive': string;
  'sortableIcons': string;
  'tableComponent': string;
  'tableContainer': string;
  'tableContent': string;
  'tableControlsContainer': string;
  'tableHeader': string;
  'tableHeaderContent': string;
  'tableHeaderItem': string;
  'tableOverflow': string;
  'tableRow': string;
  'tableRowItem': string;
  'tableRows': string;
  'tableSettings': string;
  'tableTitle': string;
  'tablerHeaderItemLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
