name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Storybook
        run: |
          yarn
          yarn build-storybook
      - name: Build and deploy to storybook-static branch
        uses: JamesIves/github-pages-deploy-action@2.0.3
        with:
          BRANCH: gh-pages
          FOLDER: storybook-static
