name: Build and Deploy
on:
  push:
#    paths: [ "src/stories/**" ] # Trigger the action only when files change in the folders defined here
    paths: [ "src/**" ] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          folder: docs-build
          clean: true
          target-folder: docs
