// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gameContainer': string;
  'playerCoin': string;
  'playerCoinsContainer': string;
  'playerContainer': string;
  'playersContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
